"""DOCX export helpers for ByteCase Notes."""
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt



def set_document_defaults(document):
    section = document.sections[0]
    section.top_margin = Inches(0.7)
    section.bottom_margin = Inches(0.7)
    section.left_margin = Inches(0.7)
    section.right_margin = Inches(0.7)

    normal = document.styles["Normal"].font
    normal.name = "Arial"
    normal.size = Pt(10)
    for style_name in ["Heading 1", "Heading 2", "Heading 3"]:
        style = document.styles[style_name]
        style.font.name = "Arial"
        style.font.bold = True


def add_department_patch(document, department):
    """Add the configured department patch/logo to the DOCX header area when available."""
    patch_path = department.get("copied_department_patch") or department.get("department_patch_path")
    if not patch_path:
        return

    path = Path(patch_path)
    if not path.exists() or not path.is_file():
        document.add_paragraph(f"Department patch/logo not embedded: file not found ({patch_path})")
        return

    try:
        paragraph = document.add_paragraph()
        paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = paragraph.add_run()
        run.add_picture(str(path), width=Inches(0.85))
    except Exception as exc:
        document.add_paragraph(f"Department patch/logo not embedded: {exc}")


def add_key_value_table(document, rows):
    table = document.add_table(rows=0, cols=2)
    table.style = "Table Grid"
    for label, value in rows:
        cells = table.add_row().cells
        cells[0].text = str(label)
        cells[1].text = str(value)
    document.add_paragraph()


def add_reference_audit_section(document, record, artifacts):
    audit = record.get("reference_audit", {})
    document.add_heading("Reference Check", level=1)
    rows = [
        ("Referenced in Notes", ", ".join(audit.get("referenced_artifact_ids", [])) or "None"),
        ("Indexed Artifacts", ", ".join(audit.get("indexed_artifact_ids", [])) or "None"),
        ("References Missing from Artifact Index", ", ".join(audit.get("missing_from_artifact_index", [])) or "None"),
        ("Indexed Artifacts Not Referenced in Notes", ", ".join(audit.get("not_referenced_in_notes", [])) or "None"),
        ("Duplicate Artifact IDs", ", ".join(audit.get("duplicate_artifact_ids", [])) or "None"),
        ("References Outside Preferred [ART-001] Format", "; ".join(audit.get("non_standard_references", [])) or "None"),
    ]
    add_key_value_table(document, rows)


def save_docx_notes(record, docx_path):
    document = Document()
    set_document_defaults(document)

    document.add_heading("ByteCase Notes Report", level=0)
    document.add_paragraph(f"Generated By: {record.get('app_name', '')} v{record.get('app_version', '')}")
    document.add_paragraph(f"Created At: {record.get('created_at', '')}")

    department = record.get("department", {})
    case_info = record.get("case_info", {})
    artifacts = record.get("artifacts", [])

    add_department_patch(document, department)

    document.add_heading("Department", level=1)
    add_key_value_table(document, [
        ("Department / Agency", department.get("department_name", "")),
        ("Unit", department.get("unit_name", "")),
        ("Department Patch / Logo", department.get("department_patch_path", "")),
        ("Copied Department Patch", department.get("copied_department_patch", "")),
        ("Department Patch Copy Error", department.get("department_patch_copy_error", "")),
    ])

    document.add_heading("Case Information", level=1)
    add_key_value_table(document, [
        ("Case Number", case_info.get("case_number", "")),
        ("Agency Case Number", case_info.get("agency_case_number", "")),
        ("Examiner", case_info.get("examiner", "")),
        ("Reviewed By", case_info.get("reviewed_by", "")),
        ("Source Description", case_info.get("source_description", "")),
        ("Examination Phase", case_info.get("examination_phase", "")),
    ])

    document.add_heading("Narrative Notes", level=1)
    narrative = record.get("narrative_notes", "")
    if narrative:
        for paragraph in narrative.split("\n"):
            document.add_paragraph(paragraph)
    else:
        document.add_paragraph("No narrative notes were entered.")

    document.add_heading("Artifact Index", level=1)
    if artifacts:
        table = document.add_table(rows=1, cols=6)
        table.style = "Table Grid"
        headers = ["ID", "Title", "Category", "Source Item", "Tool / Source", "Location"]
        for index, header in enumerate(headers):
            table.rows[0].cells[index].text = header
        for artifact in artifacts:
            cells = table.add_row().cells
            cells[0].text = artifact.get("artifact_id", "")
            cells[1].text = artifact.get("title", "")
            cells[2].text = artifact.get("category", "")
            cells[3].text = artifact.get("source_item", "")
            cells[4].text = artifact.get("tool_source", "")
            cells[5].text = artifact.get("artifact_location", "")
        document.add_paragraph()
        for artifact in artifacts:
            document.add_heading(f"{artifact.get('artifact_id', '')}: {artifact.get('title', '')}", level=2)
            add_key_value_table(document, [
                ("Date / Time", artifact.get("date_time", "")),
                ("Supporting File", artifact.get("supporting_file_path", "")),
                ("Copied Supporting File", artifact.get("copied_supporting_file", "")),
                ("Supporting File Copy Error", artifact.get("attachment_copy_error", "")),
                ("Summary", artifact.get("summary", "")),
                ("Notes", artifact.get("notes", "")),
            ])
    else:
        document.add_paragraph("No artifact references were added.")

    add_reference_audit_section(document, record, artifacts)

    limitations = record.get("limitations", "")
    if limitations:
        document.add_heading("Limitations / Review Notes", level=1)
        document.add_paragraph(limitations)

    document.add_heading("Boundary Notice", level=1)
    document.add_paragraph(record.get("boundary_notice", ""))

    document.add_paragraph("End of ByteCase Notes Report")
    document.save(docx_path)
    return Path(docx_path)
