"""Core record building and exports for ByteCase Notes."""
import json
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Tuple

from docx_exporter import save_docx_notes
from settings_service import APP_NAME, APP_VERSION, ensure_directories, safe_filename


def next_artifact_id(artifacts: List[Dict[str, str]]) -> str:
    highest = 0
    for artifact in artifacts:
        value = str(artifact.get("artifact_id", "")).upper().replace("ART-", "")
        try:
            highest = max(highest, int(value))
        except ValueError:
            continue
    return f"ART-{highest + 1:03d}"


def build_notes_record(
    settings: Dict[str, object],
    case_number: str,
    agency_case_number: str,
    examiner: str,
    reviewed_by: str,
    source_description: str,
    examination_phase: str,
    narrative_notes: str,
    artifacts: List[Dict[str, str]],
    limitations: str,
) -> Dict[str, object]:
    return {
        "app_name": APP_NAME,
        "app_version": APP_VERSION,
        "record_type": "Examiner notes workspace",
        "created_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "department": {
            "department_name": settings.get("department_name", ""),
            "unit_name": settings.get("unit_name", ""),
        },
        "case_info": {
            "case_number": case_number.strip(),
            "agency_case_number": agency_case_number.strip(),
            "examiner": examiner.strip(),
            "reviewed_by": reviewed_by.strip(),
            "source_description": source_description.strip(),
            "examination_phase": examination_phase.strip(),
        },
        "narrative_notes": narrative_notes.strip(),
        "artifacts": artifacts,
        "limitations": limitations.strip(),
        "boundary_notice": (
            "ByteCase Notes helps examiners document observations and artifact references. "
            "It does not parse evidence, determine evidentiary relevance, infer user intent, "
            "or replace examiner review."
        ),
    }


def build_txt_notes(record: Dict[str, object]) -> str:
    department = record.get("department", {})
    case_info = record.get("case_info", {})
    artifacts = record.get("artifacts", [])

    lines = []
    lines.append("BYTECASE NOTES REPORT")
    lines.append("=" * 80)
    lines.append("")
    lines.append(f"Generated By: {record.get('app_name', '')} v{record.get('app_version', '')}")
    lines.append(f"Created At: {record.get('created_at', '')}")
    lines.append(f"Department / Agency: {department.get('department_name', '')}")
    lines.append(f"Unit: {department.get('unit_name', '')}")
    lines.append("")

    lines.append("CASE INFORMATION")
    lines.append("-" * 80)
    lines.append(f"Case Number: {case_info.get('case_number', '')}")
    lines.append(f"Agency Case Number: {case_info.get('agency_case_number', '')}")
    lines.append(f"Examiner: {case_info.get('examiner', '')}")
    lines.append(f"Reviewed By: {case_info.get('reviewed_by', '')}")
    lines.append(f"Source Description: {case_info.get('source_description', '')}")
    lines.append(f"Examination Phase: {case_info.get('examination_phase', '')}")
    lines.append("")

    lines.append("NARRATIVE NOTES")
    lines.append("-" * 80)
    lines.append(record.get("narrative_notes", ""))
    lines.append("")

    lines.append("ARTIFACT INDEX")
    lines.append("-" * 80)
    if artifacts:
        for artifact in artifacts:
            lines.append(f"{artifact.get('artifact_id', '')}: {artifact.get('title', '')}")
            lines.append(f"  Category: {artifact.get('category', '')}")
            lines.append(f"  Source Item: {artifact.get('source_item', '')}")
            lines.append(f"  Tool / Source: {artifact.get('tool_source', '')}")
            lines.append(f"  Artifact Location: {artifact.get('artifact_location', '')}")
            lines.append(f"  Date / Time: {artifact.get('date_time', '')}")
            lines.append(f"  Summary: {artifact.get('summary', '')}")
            lines.append(f"  Notes: {artifact.get('notes', '')}")
            lines.append("")
    else:
        lines.append("No artifact references were added.")
        lines.append("")

    limitations = record.get("limitations", "")
    if limitations:
        lines.append("LIMITATIONS / REVIEW NOTES")
        lines.append("-" * 80)
        lines.append(limitations)
        lines.append("")

    lines.append("BOUNDARY NOTICE")
    lines.append("-" * 80)
    lines.append(record.get("boundary_notice", ""))
    lines.append("")
    lines.append("=" * 80)
    lines.append("End of ByteCase Notes Report")
    lines.append("=" * 80)
    return "\n".join(lines)


def save_notes_outputs(record: Dict[str, object], settings: Dict[str, object]) -> Dict[str, Path]:
    case_number = record.get("case_info", {}).get("case_number", "")
    source = record.get("case_info", {}).get("source_description", "")
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    base_filename = f"{safe_filename(case_number, 'NO_CASE')}_{safe_filename(source, 'notes')}_{timestamp}_notes"

    paths = ensure_directories(settings, case_number=case_number)
    outputs = {}

    json_path = paths["saved_notes_dir"] / f"{base_filename}.json"
    with json_path.open("w", encoding="utf-8") as f:
        json.dump(record, f, indent=2)
    outputs["JSON"] = json_path

    report_defaults = settings.get("report_defaults", {})
    if report_defaults.get("export_txt", True):
        txt_path = paths["reports_dir"] / f"{base_filename}.txt"
        with txt_path.open("w", encoding="utf-8") as f:
            f.write(build_txt_notes(record))
        outputs["TXT"] = txt_path

    if report_defaults.get("export_docx", True):
        docx_path = paths["reports_dir"] / f"{base_filename}.docx"
        save_docx_notes(record, docx_path)
        outputs["DOCX"] = docx_path

    return outputs
